# build the docker file, create a container and run it, create a volume for the config files to be placed at the root of the app folder
version: '3'
services:
  app:
    build: .
    container_name: TrackSeriesSaver
    volumes:
      - ./settings.yaml:/app/settings.yaml
      # add here a line for you data folder
    environment:
      TZ: "Europe/Zurich"
    restart: unless-stopped
